// Update this type when test/img content changes.
export type TestImagePath =
  | 'formats/grey6.jpg'
  | 'formats/grey8.png'
  | 'formats/grey12.jpg'
  | 'formats/grey16.png'
  | 'formats/greya16.png'
  | 'formats/greya32.png'
  | 'formats/plt-4bpp.png'
  | 'formats/plt-8bpp-color.png'
  | 'formats/rgb6.jpg'
  | 'formats/rgb12.jpg'
  | 'formats/rgb24.png'
  | 'formats/rgb48.png'
  | 'formats/rgba32.png'
  | 'formats/rgba64.png'
  | 'opencv/test.png'
  | 'opencv/testBlur.png'
  | 'opencv/testConv.png'
  | 'opencv/testGaussianBlur.png'
  | 'opencv/testRotate.png'
  | 'opencv/testRotateBicubic.png'
  | 'opencv/testRotateBilinear.png'
  | 'opencv/testTranslation.png'
  | 'grayscale_by_zimmyrose.png';
